### ISSUE TITLE
Paraview

### ISSUE THREAD

**Issue by thorade** [usnistgov/envy-mayavi#1]
Just an idea: Would it be possible to  make Coolprop and Refprop produce files that can be read directly by Paraview?
http://www.paraview.org/

**Comment by ianhbell** [comment]
Good idea.  Can you provide a sample?

**Comment by thorade** [comment]
I used to use it some time ago (to look at thermodynamic surfaces).
I just installed Paraview on my Xubuntu box and will provide a sample file in the next days. 
Basically, Paraview can read CSV, then you can apply filters and transformations and store these separately in a text file.

**Comment by ianhbell** [comment]
Interesting.  I'm building a pure-javascript version of envy as we speak (based on THREE.js).  It would be cool if we could generate a viewer-agnostic output that could be read by any of these tools.

**Comment by thorade** [comment]
Are you aware of this?
https://help.github.com/articles/3d-file-viewer/
https://help.github.com/categories/working-with-non-code-files/
Are STL or CSV sufficient for storing the information? Maybe with an accompanying json or text file?

**Comment by ianhbell** [comment]
STL are not optimal because you have to do a lot of work to construct a 3D object that looks fine (beyond the scope of the project).

For fun, I did that though :)

**Comment by thorade** [comment]
In issues/comments one cannot upload all file types, sent you an email instead.
To create a surface from a csv file with Paraview, one has to open Paraview, then load the csv file and apply filters: First, apply the Table to Points filter (make sure to keep all data arrays), then apply the Delaunay 2D filter. 
Using File -> Save/Load State one can save or load a state. A state saves the path to the input file and all applied filters. The state is saved in a xml file with extension pvsm.

![paraview_filters](https://cloud.githubusercontent.com/assets/314571/11712578/5e681092-9f2e-11e5-965c-d3591f985602.png)
